### ISSUE TITLE
Create the Intro Sequence

### ISSUE THREAD

**Issue by thaingu** [codersforcauses/foodbank#22]
Requirements

- Intro will feature a superhero banana that introduces the app with a speech box.
- Will have a fly through of tucker island.
- Up for ideas and changes

This epic is made up of these components:
- [ ] Add fly through video and transition to map
- [ ] Create banana guy introduction

**Comment by Drewbi** [comment]
I think this might just be the tucker island page. The intro can just happen over the top.
