### ISSUE TITLE
Add Five Food Groups page

### ISSUE THREAD

**Issue by thaingu** [codersforcauses/foodbank#25]
Requirements:

- Implement interactive version of this: https://www.superherofoodshq.org.au/product/five-food-groups-poster-download/
- Clicking on each section introduces them.
- Provides information on what is in the groups, why they need to be in the diet and quantity to consume.

This epic is made up of these components:

- [ ] Add food group pie chart that unlocks with locations you've visited
- [ ] Add info about the food group when clicked or hovered

**Comment by Drewbi** [comment]
Since the locations on tucker island quite closely map the food groups we could have this area be almost a recap or an unlockable tracker for the different food groups you would discover by exploring the island.
