### ISSUE TITLE
Create Authentication Pages

### ISSUE THREAD

**Issue by Drewbi** [codersforcauses/foodbank#34]
The goal is to have a child be able to sign up without needing teacher/parental assistance so we will be using just a username and potentially a birth date to signup.

Tasks to be completed:
- Start page with two options, brand new player and returning player (Use better words)
- #43: Signup page
- Login page

**Comment by milayue** [comment]
AWS or Google Firebase?

**Comment by Drewbi** [comment]
I haven't looked into it yet but firebase could be very useful in this case.

**Comment by DBprassan12** [comment]
Irrelevant to the project anyone
