### ISSUE TITLE
Add tucker island map to homepage

### ISSUE THREAD

**Issue by Drewbi** [codersforcauses/foodbank#41]
## Task

The main map needs to be added to the homepage.

## Implementation

Since we will need to have the map move later when we add mobile support I would use either an img tag or use css to set it as a background image. The empty ocean part may come in handy if we need introductory dialog on the right side but otherwise it should be removed. 

## Other Considerations

We will be adding locations separately over the top so we need the map to stay consistently positioned relative to something. We will also be getting a map version without towns or names but this can be substituted later.

[Here](https://www.dropbox.com/sh/5fkv4xg37f8xc33/AACEg0lMlr4gAFy0pwA1ZdNka/Images?dl=0&preview=Map+180509.jpg&subfolder_nav_tracking=1) is the file.

### References

Epic: #24
Pull Requests:

**Comment by CodeWithTheDoctor** [comment]
Issue completed.
