### ISSUE TITLE
Add clickable towns to map

### ISSUE THREAD

**Issue by Drewbi** [codersforcauses/foodbank#42]
## Task

Each town/location on tucker island should be a clickable element and should be overlaid in it's original position.

## Implementation

As the assets are not svgs we will probably use img tags and not worry about adding border effects. The elements can all be added using a town component that can take an image and positional data as props. We will also need to add a title for each one as this is not included in the asset.

## Other Considerations

Getting the positions correct will be an interesting challenge when catering to different device sizes and we will also need to consider how the positions will change for mobile phones when the map is split between two views.

[Here](https://www.dropbox.com/sh/5fkv4xg37f8xc33/AAD65pWImr_Q6wnLaDgSzcb8a/Map%20Locations?dl=0&subfolder_nav_tracking=1) are the assets.

## References

Epic: #24 
Pull Requests:

**Comment by innoc3ntt** [comment]
how to resize image to device width?
use setHeight to scale the area coords on map element
css stuff for the pop up
