### ISSUE TITLE
Redesign the Navbar component

### ISSUE THREAD

**Issue by JeremiahPinto** [codersforcauses/foodbank#73]
Create a navbar component that only shows when the user accesses the site on desktops/large screens.

The navbar should:
- [x] use semantic HTML (`header`, `nav`, etc)
- [x] should be fixed to the top of the page
- [x] follow theme given (background colour be primary or neutral)
- [x] create nav-link component (the buttons in the navbar). According to [superherofoods](https://www.superherofoodshq.org.au/home/), the text uses the font `Abraham`. Use the class `font-serif` to achieve this.
- [x] <del>render the component in storybook<del>
- [x] have a dropdown menu button
  * The dropdown menu should have the options:
    * Tucker Island
    * Recipes
    * Drag-Drop game (Yet to decide on a name for the game.)
    * Trophy
- [x] have a working sign-in button
  * Should open sign in form. (Sign in form component has already been made)
  * If user is signed in, then it should display the username of the user with a dropdown arrow next to it, which should bring down a sign out button when hovers over it.

Try making the designs similar to:

![image](https://user-images.githubusercontent.com/22740095/143574203-db94261a-5dd9-4cc5-8234-7a6970e8bcc2.png)

![image](https://user-images.githubusercontent.com/22740095/143575154-1d039090-2d94-4240-90f5-ae3961e34435.png)

**Comment by CodeWithTheDoctor** [comment]
Needs updates, as suggested by Jerry: 

- Dont use tailwind triangle... just use CSS for the triangles. You dont need an entire library for three lines.

- On Safari, the styling of the Navbar is off. Menu icon isnt centered, and opacity is messed up.

- Style the 'focus' psuedoclass.

- Need more spacing between menu and sign-in button.
